server {
  listen 80;
  server_name _;

  proxy_hide_header 'Access-Control-Allow-Origin';
  proxy_hide_header 'Access-Control-Allow-Methods';
  proxy_hide_header 'Access-Control-Allow-Headers';

  add_header Access-Control-Allow-Origin "*" always;
  add_header Access-Control-Allow-Methods "GET,POST,OPTIONS" always;
  add_header Access-Control-Allow-Headers "*" always;

  port_in_redirect off;
  absolute_redirect off;

  include /etc/nginx/includes/services.conf;

  location = /health { return 200 "ok\n"; }
}