version: '2.2'

services:

  blazegraph:
    container_name: ${COMPOSE_PROJECT_NAME}-blazegraph
    environment:
      QUERY_TIMEOUT: '0'
    image: ${BLAZEGRAPH_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    ports:
      - ${PORT_BLAZEGRAPH}:8080
    volumes:
      - ${DIRECTORY_BLAZEGRAPH_DATA}:/blazegraph-data:rw
      - ${DIRECTORY_BLAZEGRAPH_EXCHANGE}:/blazegraph-exchange:rw

  metaphactory:
    container_name: ${COMPOSE_PROJECT_NAME}-metaphactory
    depends_on:
      blazegraph:
        condition: service_started
    image: ${METAPHACTORY_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    ports:
      - ${PORT_RDS}:8080
    volumes:
    - ${DIRECTORY_METAPHACTORY_RUNTIME}:/runtime-data:rw