services:

  metaphactory:
    container_name: ${COMPOSE_PROJECT_NAME}-metaphactory
    depends_on:
      qlever:
        condition: service_started
    environment:
      METAPHACTORY_OPTS: METAPHACTORY_OPTS=-Dconfig.storage.rds-global.type=nonVersionedFile -Dconfig.storage.rds-global.mutable=true -Dconfig.storage.rds-global.root=/rdsapps/rds-global
    image: ${METAPHACTORY_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    ports:
      - ${PORT_RDS}:8080
    volumes:
      - ${DIRECTORY_METAPHACTORY_RUNTIME}:/runtime-data:rw

  jobs:
    container_name: ${COMPOSE_PROJECT_NAME}-jobs
    build: ./services/jobs
    image: swissartresearx/rds-global-jobs
    environment:
      GITHUB_USERNAME_SIKART: ${GITHUB_USERNAME_SIKART}
      GITHUB_TOKEN_SIKART: ${GITHUB_TOKEN_SIKART}
      QLEVER_ACCESS_TOKEN: ${QLEVER_ACCESS_TOKEN}
    ports:
      - "8088:80"
    volumes:
      - ./services/jobs/pipeline:/pipeline
      - ./data:/data

  qlever:
    container_name: ${COMPOSE_PROJECT_NAME}-qlever
    build: ./services/qlever
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    restart: unless-stopped
    ports:
      - "7001:7001"
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: /index
    # First start: create index using `qlever index`
    volumes:
      - ./binds/qlever-index:/index:rw
      - ./data:/index/data
      - ./services/qlever/rds/Qleverfile:/index/Qleverfile:ro