services:
  jobs:
    restart: unless-stopped

  opensearch-connector:
    restart: unless-stopped
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${RECONCILE_HOST_NAME}
      VIRTUAL_HOST: ${RECONCILE_HOST_NAME}
      VIRTUAL_PORT: 8000
      X_FRAME_OPTIONS: "off"
    command: ["--opensearch-url", "http://opensearch-node:9200", "--index", "rds-entities", "--port", "8000", "--config", "/config/datasets.yml", "--datasets", "${DATASETS}", "--reconciliation-base-url", "https://${RECONCILE_HOST_NAME}"]
    networks:
      - internal
      - proxy

  opensearch-node:
    restart: unless-stopped
  opensearch-dashboard:
    restart: unless-stopped

  platform:
    restart: unless-stopped
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${PLATFORM_HOST_NAME}
      VIRTUAL_HOST: ${PLATFORM_HOST_NAME}
      VIRTUAL_PORT: 8080
      CONTENT_SECURITY_POLICY: "default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: ; img-src 'self' https: data: blob:; connect-src 'self'; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"
    networks:
      - internal
      - proxy
      
  qlever:
    restart: unless-stopped
  

networks:
  proxy:
    name: ${PROXY_NETWORK_NAME}
    external: true
