services:

  jobs:
    container_name: ${COMPOSE_PROJECT_NAME}-jobs
    build: ./services/jobs
    image: swissartresearx/rds-global-jobs
    environment:
      GITHUB_USERNAME_SIKART: ${GITHUB_USERNAME_SIKART}
      GITHUB_TOKEN_SIKART: ${GITHUB_TOKEN_SIKART}
      QLEVER_ACCESS_TOKEN: ${QLEVER_ACCESS_TOKEN}
    volumes:
      - ./services/jobs/pipeline:/pipeline
      - ./data:/data

  blazegraph:
    container_name: ${COMPOSE_PROJECT_NAME}-blazegraph
    environment:
      JAVA_OPTS: -Xmx24g
      QUERY_TIMEOUT: '0'
    image: robcast/researchspace-blazegraph:2.2.0-jre17
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    restart: unless-stopped
    volumes:
      - ${DIRECTORY_BLAZEGRAPH_DATA}:/blazegraph-data:rw
      - ${DIRECTORY_BLAZEGRAPH_EXCHANGE}:/blazegraph-exchange:rw

  platform:
    container_name: ${COMPOSE_PROJECT_NAME}-platform
    depends_on:
      qlever:
        condition: service_started
    environment:
      PLATFORM_OPTS: >-
        -Dconfig.environment.sparqlEndpoint=http://blazegraph:8080/blazegraph/sparql
        -Dlog4j.configurationFile=classpath:org/researchspace/logging/log4j2.xml
        ${RESEARCHSPACE_OPTS}
      JAVA_OPTS: -Xmx1g
    image: swissartresearx/researchspace:7fa27dd39c4a02d3cf39b02f50162faed3eab8dd
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    ports:
      - ${PORT_RDS}:8080
    volumes:
     - ${DIRECTORY_PLATFORM_RUNTIME}:/runtime-data:rw
     - ./services/platform/apps:/apps

  qlever:
    container_name: ${COMPOSE_PROJECT_NAME}-qlever
    build: ./services/qlever
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    restart: unless-stopped
    ports:
      - ${PORT_TRIPLESTORE}:7001
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: /index
    # First start: create index using `qlever index`
    volumes:
      - ./binds/qlever-index:/index:rw
      - ./data:/index/data
      - ./services/qlever/rds/Qleverfile:/index/Qleverfile:ro