services:
  opensearch-dashboard:
    ports:
      - 127.0.0.1:${PORT_OPENSEARCH_DASHBOARD:-5601}:5601

  opensearch-node:
    ports:
      - 127.0.0.1:${PORT_OPENSEARCH:-9200}:9200
  
  platform:
    ports:
      - ${PORT_RDS:-8080}:8080
  qlever:
    ports:
      - ${PORT_QLEVER_RDS:-7001}:7001