services:
  jobs:
    container_name: ${COMPOSE_PROJECT_NAME}-jobs
    build: ./services/jobs
    environment:
      DATASETS: ${DATASETS}
      GITHUB_USERNAME_SIKART: ${GITHUB_USERNAME_SIKART}
      GITHUB_TOKEN_SIKART: ${GITHUB_TOKEN_SIKART}
      QLEVER_ACCESS_TOKEN: ${QLEVER_ACCESS_TOKEN}
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ./binds/qlever:/index:rw
      - ./services/jobs/pipeline:/pipeline
      - ./config:/config
      - ./data:/data:delegated

  platform:
    container_name: ${COMPOSE_PROJECT_NAME}-platform
    environment:
      PLATFORM_OPTS: >-
        -Dlog4j.configurationFile=classpath:org/researchspace/logging/log4j2.xml
        ${RESEARCHSPACE_OPTS:-}
      JAVA_OPTS: -Xmx1g
    image: swissartresearx/researchspace:535745857b7ca29f7bb21d121b0fad518dfc1d76
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    ports:
      - ${PORT_RDS}:8080
    volumes:
     - ${DIRECTORY_PLATFORM_RUNTIME}:/runtime-data:rw
     - ./services/platform/apps:/apps

  qlever:
    container_name: ${COMPOSE_PROJECT_NAME}-qlever
    build: ./services/qlever
    environment:
      QLEVER_ACCESS_TOKEN: ${QLEVER_ACCESS_TOKEN}
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    ports:
      - ${PORT_QLEVER_RDS}:7001
    volumes:
      - ./binds/qlever:/index:rw
      - ./data:/data