server {
    listen 80;
    root /data;

    autoindex on;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    send_timeout 24h;

    keepalive_timeout 75s;

    aio threads;
    directio 8m;

    include /etc/nginx/conf.d/mime.types;

    location / {
        try_files $uri $uri/ =404;
    }
}