import argparse
import yaml
from pathlib import Path

from lib.utils import load_config

GENERATED_HEADER = (
    "# This file is automatically generated.\n"
    "# Do not edit it manually.\n\n"
)


class LiteralBlockDumper(yaml.SafeDumper):
    pass


def representString(dumper: LiteralBlockDumper, data: str):
    if "\n" in data:
        normalised = "\n".join(line.rstrip() for line in data.splitlines()) + "\n"
        return dumper.represent_scalar(
            "tag:yaml.org,2002:str",
            normalised,
            style="|",
        )
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


LiteralBlockDumper.add_representer(str, representString)


def parseActiveDatasets(datasets: str | None) -> list[str] | None:
    if not datasets:
        return None

    active_datasets = []
    for dataset_id in datasets.split(","):
        dataset_id = dataset_id.strip()
        if dataset_id and dataset_id not in active_datasets:
            active_datasets.append(dataset_id)
    return active_datasets


def loadDatasetDefinitions(datasets_directory: Path) -> dict:
    dataset_definitions = {}

    for dataset_file in sorted(datasets_directory.glob("*.yml")):
        config = load_config(dataset_file) or {}
        datasets = config.get("datasets", {})

        for dataset_id, dataset_config in datasets.items():
            if dataset_id in dataset_definitions:
                raise ValueError(
                    f"Duplicate dataset key '{dataset_id}' found in {dataset_file}"
                )
            dataset_definitions[dataset_id] = dataset_config

    return dataset_definitions


def generateDatasetsConfiguration(*, datasets_directory: str,types_config: str, output_file: str, datasets: str | None = None) -> None:
    datasets_directory_path = Path(datasets_directory)
    if not datasets_directory_path.exists():
        raise FileNotFoundError(
            f"Datasets directory not found: {datasets_directory_path}"
        )

    types_config_path = Path(types_config)
    if not types_config_path.exists():
        raise FileNotFoundError(f"Types configuration not found: {types_config_path}")

    dataset_definitions = loadDatasetDefinitions(datasets_directory_path)
    active_datasets = parseActiveDatasets(datasets)

    if active_datasets is None:
        selected_datasets = dataset_definitions
    else:
        missing_datasets = [
            dataset_id
            for dataset_id in active_datasets
            if dataset_id not in dataset_definitions
        ]
        if missing_datasets:
            missing_keys = ", ".join(missing_datasets)
            raise KeyError(f"Unknown dataset key(s) requested: {missing_keys}")

        selected_datasets = {
            dataset_id: dataset_definitions[dataset_id] for dataset_id in active_datasets
        }

    types_config_data = load_config(types_config_path) or {}

    assembled_config = {
        "datasets": selected_datasets,
        "types": types_config_data.get("types", {}),
    }

    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rendered_yaml = yaml.dump(
        assembled_config,
        sort_keys=False,
        allow_unicode=True,
        width=1000,
        Dumper=LiteralBlockDumper,
    )
    output_path.write_text(GENERATED_HEADER + rendered_yaml, encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate the datasets YAML configuration from dataset fragments")
    parser.add_argument("--datasets-directory", required=True, help="Directory containing per-dataset YAML configuration files")
    parser.add_argument("--types-config", required=True, help="Path to the shared types YAML configuration")
    parser.add_argument("--output-file", required=True, help="Path to the generated datasets YAML configuration")
    parser.add_argument("--datasets", required=False, help="Comma-separated list of active datasets. Defaults to all configured datasets.")

    args = parser.parse_args()

    generateDatasetsConfiguration(
        datasets_directory=args.datasets_directory,
        types_config=args.types_config,
        output_file=args.output_file,
        datasets=args.datasets,
    )
