datasets:

  aat:
    name: AAT
    description: Getty Art & Architecture Thesaurus
    source:
      - url: http://aatdownloads.getty.edu/VocabData/explicit.zip
        process:
        - unzip
    graph: http://vocab.getty.edu/aat/graph
    namespace: http://vocab.getty.edu/aat/
    prefixes:
      gvp: http://vocab.getty.edu/ontology#
      skos: http://www.w3.org/2004/02/skos/core#
      xl: http://www.w3.org/2008/05/skos-xl#
    types:
      Type:
        - gvp:Concept
    queries:
      description: |
        ?subject gvp:parentStringAbbrev ?value .
      prefLabel: |
        ?subject gvp:prefLabelGVP/xl:literalForm ?value .
      labels: |
        ?subject (gvp:prefLabelGVP | xl:prefLabel | xl:altLabel)/xl:literalForm ?value .
      matches: |
        ?subject (skos:exactMatch | skos:closeMatch) ?value .
    wikidata_match_property: P1014

  bso:
    name: BSO
    graph: http://bso.swissartresearch.net/graph
    namespace: https://resource.swissartresearch.net
    prefixes:
      crmdig: http://www.ics.forth.gr/isl/CRMdig/
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      gndo: https://d-nb.info/standards/elementset/gnd#
      crm: http://www.cidoc-crm.org/cidoc-crm/
      schema: http://schema.org/
      skos: http://www.w3.org/2004/02/skos/core#
      search: https://platform.swissartresearch.net/search/
    source:
      - endpoint: https://bso.swissartresearch.net/sparql
        type: construct_query
        page_size: 1000
        query: |
          CONSTRUCT {
            ?s ?p ?o.
            ?sameas gndo:biographicalOrHistoricalInformation ?description .
            ?identifier rdfs:label ?label .
          } WHERE {
            ?s a search:Person ;
              skos:prefLabel ?prefLabel ;
              crm:P1_is_identified_by ?identifier ;
              crmdig:L54_is_same-as ?sameas .
            ?sameas gndo:biographicalOrHistoricalInformation ?description .
            ?identifier rdfs:label ?label .
            ?s ?p ?o.
          }
        process:
          - gunzip   
    types:
      Person:
        - crm:E21_Person
    queries:
      prefLabel: |
        ?subject skos:prefLabel ?value .
      labels: |
        ?subject crm:P1_is_identified_by/rdfs:label ?value .
      description: |
        ?subject crmdig:L54_is_same-as/gndo:biographicalOrHistoricalInformation ?value .
      matches: |
        ?subject crmdig:L54_is_same-as ?value .
  
  geonames:
    name: GeoNames
    source:
      - url: http://download.geonames.org/all-geonames-rdf.zip
        process:
          - unzip
          - rdfxml2nt
    graph: http://sws.geonames.org/graph
    namespace: https://sws.geonames.org/
    prefixes:
      gn: http://www.geonames.org/ontology#
      owl: http://www.w3.org/2002/07/owl#
      rdfs: http://www.w3.org/2000/01/rdf-schema#
    types:
      Place:
        - gn:Feature
    queries:
      description: |
        ?subject gn:parentADM1/gn:name ?adm1 .
        ?subject gn:parentCountry/gn:name ?country .
        BIND(CONCAT(?adm1, ", ", ?country) as ?value )
      prefLabel: |
        ?subject gn:name ?value .
      labels: |
        ?subject gn:alternateName ?value .
      matches: |
        ?subject rdfs:seeAlso ?value .
    wikidata_match_property: P1566

  gnd:
    name: GND
    source:
      - type: http_file
        url: https://data.dnb.de/opendata/authorities-gnd_lds.nt.gz
        process:
          - gunzip   
      - type: http_file
        url: https://raw.githubusercontent.com/deutsche-nationalbibliothek/gnd-ontology/refs/heads/main/source/gnd.ttl
        file_format: ttl
    graph: https://d-nb.info/gnd/authorities/graph
    namespace: https://d-nb.info/gnd/
    prefixes:
      gnd: https://d-nb.info/standards/elementset/gnd#
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      schema: http://schema.org/
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      BibliographicItem:
        - gnd:Work
      Event:
        - gnd:ConferenceOrEvent
      Group:
        - gnd:CorporateBody
      Person:
        - gnd:Person
      Place:
        - gnd:PlaceOrGeographicName
      Type:
        - gnd:SubjectHeading
    queries:
      description: |
            OPTIONAL {
              ?subject gnd:definition|gnd:note|gnd:biographicalOrHistoricalInformation ?bio .
            }
            OPTIONAL { ?subject gnd:professionOrOccupationAsLiteral ?profession }
            
            OPTIONAL { ?subject gnd:dateOfBirth ?bDate }
            OPTIONAL { ?subject gnd:placeOfBirth ?pb . ?pb gnd:preferredNameForThePlaceOrGeographicName ?bPlace }
            OPTIONAL { ?subject gnd:dateOfDeath ?dDate }
            OPTIONAL { ?subject gnd:placeOfDeath ?pd . ?pd gnd:preferredNameForThePlaceOrGeographicName ?dPlace }

            BIND(CONCAT(
              COALESCE(?bio, ""),
              IF(BOUND(?profession), CONCAT(" ", ?profession), ""),
              IF(BOUND(?bDate) || BOUND(?bPlace) || BOUND(?dDate) || BOUND(?dPlace),
                CONCAT(" (", 
                        COALESCE(STR(?bDate), ""), IF(BOUND(?bPlace), CONCAT(", ", ?bPlace), ""),
                        " – ", 
                        COALESCE(STR(?dDate), ""), IF(BOUND(?dPlace), CONCAT(", ", ?dPlace), ""),
                        ")"),
                "")
            ) AS ?value)
      prefLabel: |
        ?subject ?predicatePrefLabel ?value .
        ?predicatePrefLabel rdfs:subPropertyOf gnd:preferredName .
      labels: |
        ?subject ?predicatePrefLabel ?value .
        ?predicatePrefLabel rdfs:subPropertyOf gnd:variantName .
      types: |
        { ?subject a ?value } UNION { ?subject a/rdfs:subClassOf ?value } .
      matches: |
        ?subject ?predicate ?value .
        VALUES (?predicate) {
          (schema:sameAs)
          (rdfs:seeAlso)
          (skos:exactMatch)
        }
    wikidata_match_property: P227

  grp:
    name: GRP
    description: Gta Research Portal
    graph: https://data.gta.arch.ethz.ch/graph/
    namespace: https://resource.gta.arch.ethz.ch/
    prefixes:
      aat: http://vocab.getty.edu/aat/
      crmdig: http://www.ics.forth.gr/isl/CRMdig/
      crm: http://www.cidoc-crm.org/cidoc-crm/
      type: https://data.gta.arch.ethz.ch/type/
    source:
      - endpoint: https://researchportal.gta.arch.ethz.ch/sparql
        type: construct_query
        page_size: 1000
        query: |
          CONSTRUCT {
            ?s a ?type ;
              rdfs:label ?label ;
              crm:P1_is_identified_by ?identifier, ?primaryIdentifier ;
              crmdig:L54_is_same-as ?sameas .
            ?identifier crm:P2_has_type ?identifierType ;
              crm:P190_has_symbolic_content ?identifierValue .
          } WHERE {
            VALUES (?type) { (crm:E21_Person) (crm:E74_Group) }
            ?s a ?type ;
              rdfs:label ?label ;
              crm:P1_is_identified_by ?identifier, ?primaryIdentifier ;
              crmdig:L54_is_same-as ?sameas .
            ?identifier crm:P2_has_type ?identifierType ;
              crm:P190_has_symbolic_content ?identifierValue .
          }
        process:
          - gunzip   
    types:
      Group:
        - crm:E74_Group
      Person:
        - crm:E21_Person
    queries:
      prefLabel: |
        ?subject crm:P1_is_identified_by ?identifier .
        ?identifier crm:P2_has_type aat:300404670 ;
          crm:P190_has_symbolic_content ?value .
      labels: |
        ?subject rdfs:label ?label .
      description: |
        ?subject crm:P67i_is_referred_to_by ?statement .
        ?statement crm:P2_has_type type:4149527 ;
          crm:P190_has_symbolic_content ?value .
      matches: |
        ?subject crmdig:L54_is_same-as ?value .

  lcnaf:
    name: LCNAF
    description: Library of Congress Name Authority File
    source:
      - type: http_file
        url: https://id.loc.gov/download/authorities/names.skosrdf.ttl.gz
        file_format: ttl
        process:
          - gunzip
    file_format: ttl
    graph: http://id.loc.gov/authorities/names/graph
    namespace: http://id.loc.gov/authorities/names/
    prefixes:
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      Person:
        - skos:Concept
    queries:
      description: |
        ?subject skos:note ?value .
      prefLabel: |
        ?subject skos:prefLabel ?value .
      labels: |
        ?subject (skos:prefLabel | skos:altLabel) ?value .
      matches: |
        ?subject skos:exactMatch ?value .
    wikidata_match_property: P244


  sikart:
    name: SIKART
    source:
      - type: github_zip
        repository: swiss-art-research-net/sikart-data
        path: source/SIK_20210616_2300.ttl.zip
        file_format: ttl
        process:
          - unzip
    file_format: ttl
    graph: http://recherche.sik-isea.ch/graph
    namespace: https://recherche.sik-isea.ch/person-
    prefixes:
      crm: http://www.cidoc-crm.org/cidoc-crm/
      crmdig: http://www.ics.forth.gr/isl/CRMdig/
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      sik: https://recherche.sik-isea.ch/
    types:
      Artwork:
        - sik:SIK-WORK
        - sik:SIK-WORK_GROUP
        - sik:SIK-PARENT_WORK
      Person:
        - sik:SIK-ACTOR
      Type:
        - sik:SIK-TYPE
    queries:
      description: |
        ?subject crm:P67i_is_referred_to_by ?statement .
        ?statement crm:P2_has_type ?type ;
                  rdfs:label ?value .
        VALUES ?type {
          sik:type-BIOGRAPHICAL_DATA
          sik:type-BRIEF_BIOGRAPHY
        }
      prefLabel: |
        ?subject crm:P1_is_identified_by/rdfs:label ?value .
      labels: |
        ?subject crm:P1_is_identified_by/rdfs:label ?value .
      matches:
        ?subject crmdig:L54_same_as ?value .
    wikidata_match_property: P781

  thesarchesp:
    name: ThesArchEsp
    source:
      - url: http://data.culture.fr/thesaurus/data/ark:/67717/T96?includeSchemes=true&format=TURTLE
        type: http_file
        file_format: ttl
    file_format: ttl
    graph: http://data.culture.fr/thesaurus/resource/ark:/67717/T96/graph
    namespace: http://data.culture.fr/thesaurus/resource/ark:/67717/T96/
    prefixes:
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      Type:
        - skos:Concept
    queries:
      description: |
        ?subject skos:definition ?value .
      prefLabel: |
        ?subject skos:prefLabel ?value .
      labels: |
        ?subject (skos:prefLabel | skos:altLabel) ?value .
      matches: |
        ?subject skos:exactMatch ?value .

  thesobjmob:
    name: ThesObjMob
    source:
      - url: http://data.culture.fr/thesaurus/data/ark:/67717/T69?includeSchemes=true&format=TURTLE
        type: http_file
        file_format: ttl
    file_format: ttl
    graph: http://data.culture.fr/thesaurus/resource/ark:/67717/T69/graph
    namespace: http://data.culture.fr/thesaurus/resource/ark:/67717/T69/
    prefixes:
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      Type:
        - skos:Concept
    queries:
      description: |
        ?subject skos:definition ?value .
      prefLabel: |
        ?subject skos:prefLabel ?value .
      labels: |
        ?subject (skos:prefLabel | skos:altLabel) ?value .
      matches: |
        ?subject skos:exactMatch ?value .

  ulan:
    name: ULAN
    source:
      - url: http://ulandownloads.getty.edu/VocabData/full.zip
        process:
          - unzip
    graph: http://vocab.getty.edu/ulan/graph
    namespace: http://vocab.getty.edu/ulan/
    prefixes:
      gvp: http://vocab.getty.edu/ontology#
      skos: http://www.w3.org/2004/02/skos/core#
      xl: http://www.w3.org/2008/05/skos-xl#
    types:
      Person:
        - gvp:PersonConcept
        - gvp:UnknownPersonConcept
    queries:
      description: |
        ?subject gvp:parentStringAbbrev ?value .
      prefLabel: |
        ?subject gvp:prefLabelGVP/xl:literalForm ?value .
      labels: |
        ?subject (gvp:prefLabelGVP | xl:prefLabel | xl:altLabel)/xl:literalForm ?value .
      matches: |
        ?subject (skos:exactMatch | skos:closeMatch) ?value .
    wikidata_match_property: P245

  wikidata:
    name: Wikidata
    source:
      - type: http_file
        url: https://github.com/swiss-art-research-net/rds-wikidata-fetcher/releases/download/v0.1/artists.ttl.gz
        process:
          - gunzip
      - type: http_file
        url: https://github.com/swiss-art-research-net/rds-wikidata-fetcher/releases/download/v0.1/aatTerms.ttl.gz
        process:
          - gunzip
      - type: http_file
        url: https://github.com/swiss-art-research-net/rds-wikidata-fetcher/releases/download/v0.1/gndTerms.ttl.gz
        process:
          - gunzip
      - type: http_file
        url: https://github.com/swiss-art-research-net/rds-wikidata-fetcher/releases/download/v0.1/lcnafPersons.ttl.gz
        process:
          - gunzip
      - type: http_file
        url: https://github.com/swiss-art-research-net/rds-wikidata-fetcher/releases/download/v0.1/ulanPersons.ttl.gz
        process:
          - gunzip
    graph: http://www.wikidata.org/graph
    namespace: http://www.wikidata.org/entity/
    prefixes:
      wd: http://www.wikidata.org/entity/
      wdt: http://www.wikidata.org/prop/direct/
      rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      rds: http://schema.swissartresearch.net/ontology/rds#
      schema: http://schema.org/
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      BibliographicItem:
        - rds:BibliographicItem
      Event:
        - rds:Event
      Group:
        - rds:Group
      Person:
        - wd:Q5
        - rds:Person
      Place:
        - rds:Place
      Type:
        - rds:Type
    queries:
      prefLabel: |
        ?subject rdfs:label ?value .
        FILTER(LANG(?value) = "en" )
      labels: |
        ?subject rdfs:label ?value .
      description: |
        ?subject schema:description ?value .
        FILTER(LANG(?value) = "en")
      matches: |
        ?subject owl:sameAs ?value .

types:
  Artwork:
    name: Artwork
  BibliographicItem:
    name: Bibliographic Item
  Event:
    name: Event
  Group:
    name: Group
  Person:
    name: Person
  Place:
    name: Place
  Type:
    name: Type
