datasets:

  aat:
    source:
      - url: http://aatdownloads.getty.edu/VocabData/explicit.zip
        process:
        - unzip
    graph: http://vocab.getty.edu/aat/graph
    namespace: http://vocab.getty.edu/aat/
    prefixes:
      gvp: http://vocab.getty.edu/ontology#
      skos: http://www.w3.org/2004/02/skos/core#
      xl: http://www.w3.org/2008/05/skos-xl#
    types:
      Type:
        - gvp:Concept
    queries:
      description: |
        ?subject gvp:parentStringAbbrev ?value .
      prefLabel: |
        ?subject gvp:prefLabelGVP/xl:literalForm ?value .
      labels: |
        ?subject (gvp:prefLabelGVP | xl:prefLabel | xl:altLabel)/xl:literalForm ?value .
      matches: |
        ?subject (skos:exactMatch | skos:closeMatch) ?value .
    wikidata_match_property: P1014

  geonames:
    source:
      - url: http://download.geonames.org/all-geonames-rdf.zip
        process:
          - unzip
          - rdfxml2nt
    graph: http://sws.geonames.org/graph
    namespace: https://sws.geonames.org/
    prefixes:
      gn: http://www.geonames.org/ontology#
      owl: http://www.w3.org/2002/07/owl#
    types:
      Place:
        - gn:Feature
    queries:
      description: |
        BIND("" AS ?value) .
      prefLabel: |
        ?subject gn:name ?value .
      labels: |
        ?subject gn:alternateName ?value .
      matches: |
        ?subject owl:sameAs ?value .
    wikidata_match_property: P1566

  gnd:
    source:
      - type: http_file
        url: https://data.dnb.de/opendata/authorities-gnd_lds.nt.gz
        process:
          - gunzip   
      - type: http_file
        url: https://raw.githubusercontent.com/deutsche-nationalbibliothek/gnd-ontology/refs/heads/main/source/gnd.ttl
        file_format: ttl
    file_format: ttl
    graph: https://d-nb.info/gnd/authorities/graph
    namespace: https://d-nb.info/gnd/
    prefixes:
      gnd: https://d-nb.info/standards/elementset/gnd#
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      schema: http://schema.org/
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      BibliographicItem:
        - gnd:Work
      Event:
        - gnd:ConferenceOrEvent
      Group:
        - gnd:CorporateBody
      Person:
        - gnd:Person
      Place:
        - gnd:PlaceOrGeographicName
      Type:
        - gnd:SubjectHeading
    queries:
      description: |
        ?subject ?predicateDescription ?value .
        VALUES (?predicateDescription) {
            ( <https://d-nb.info/standards/elementset/gnd#definition> )
            ( <https://d-nb.info/standards/elementset/gnd#note> )
            ( <https://d-nb.info/standards/elementset/gnd#biographicalOrHistoricalInformation> )
            ( <https://d-nb.info/standards/elementset/gnd#professionOrOccupationAsLiteral> )
        }
      prefLabel: |
        ?subject ?predicatePrefLabel ?value .
        ?predicatePrefLabel rdfs:subPropertyOf gnd:preferredName .
      labels: |
        ?subject ?predicatePrefLabel ?value .
        ?predicatePrefLabel rdfs:subPropertyOf gnd:variantName .
      type:
        ?subject a/rdfs:subClassOf? ?value .
      matches: |
        ?subject ?predicate ?value .
        VALUES (?predicate) {
          (schema:sameAs)
          (rdfs:seeAlso)
          (skos:exactMatch)
        }
    wikidata_match_property: P227

  sikart:
    source:
      - type: github_zip
        repository: swiss-art-research-net/sikart-data
        path: source/SIK_20210616_2300.ttl.zip
        file_format: ttl
        process:
          - unzip
    file_format: ttl
    graph: http://recherche.sik-isea.ch/graph
    prefixes:
      crm: http://www.cidoc-crm.org/cidoc-crm/
      crmdig: http://www.ics.forth.gr/isl/CRMdig/
      rdfs: http://www.w3.org/2000/01/rdf-schema#
      sik: https://recherche.sik-isea.ch
    types:
      Artwork:
        - sik:SIK-WORK
        - sik:SIK-WORK_GROUP
        - sik:SIK-PARENT_WORK
      BibliographicItem:
        - sik:SIK-DOCUMENT
        - sik:SIK-PUBLICATION
        - sik:SIK-PARENT_DOCUMENT
      Event:
        - sik:SIK-EXHIBITION
        - sik:SIK-AWARD_CEREMONY
      Person:
        - sik:SIK-ACTOR
      Place: 
        - crm:E53_Place
      Type:
        - sik:SIK-TYPE
    queries:
      description: |
        BIND("" AS ?value) .
      prefLabel: |
        ?subject crm:P1_is_identified_by/rdfs:label ?value .
      labels: |
        ?subject crm:P1_is_identified_by/rdfs:label ?value .
      matches:
        ?subject crmdig:L54_is_same-as ?value .


  thesarchesp:
    source:
      - url: http://data.culture.fr/thesaurus/data/ark:/67717/T96?includeSchemes=true&format=TURTLE
        type: http_file
        file_format: ttl
    file_format: ttl
    graph: http://data.culture.fr/thesaurus/resource/ark:/67717/T96/graph
    prefixes:
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      Type:
        - skos:Concept
    queries:
      description: |
        ?subject skos:definition ?value .
      prefLabel: |
        ?subject skos:prefLabel ?value .
      labels: |
        ?subject (skos:prefLabel | skos:altLabel) ?value .
      matches: |
        ?subject skos:exactMatch ?value .

  thesobjmob:
    source:
      - url: http://data.culture.fr/thesaurus/data/ark:/67717/T69?includeSchemes=true&format=TURTLE
        type: http_file
        file_format: ttl
    file_format: ttl
    graph: http://data.culture.fr/thesaurus/resource/ark:/67717/T69/graph
    prefixes:
      skos: http://www.w3.org/2004/02/skos/core#
    types:
      Type:
        - skos:Concept
    queries:
      description: |
        ?subject skos:definition ?value .
      prefLabel: |
        ?subject skos:prefLabel ?value .
      labels: |
        ?subject (skos:prefLabel | skos:altLabel) ?value .
      matches: |
        ?subject skos:exactMatch ?value .

  ulan:
    source:
      - url: http://ulandownloads.getty.edu/VocabData/full.zip
        process:
          - unzip
    graph: http://vocab.getty.edu/ulan/graph
    namespace: http://vocab.getty.edu/ulan/
    prefixes:
      gvp: http://vocab.getty.edu/ontology#
      skos: http://www.w3.org/2004/02/skos/core#
      xl: http://www.w3.org/2008/05/skos-xl#
    types:
      Person:
        - gvp:PersonConcept
        - gvp:UnknownPersonConcept
    queries:
      description: |
        ?subject gvp:parentStringAbbrev ?value .
      prefLabel: |
        ?subject gvp:prefLabelGVP/xl:literalForm ?value .
      labels: |
        ?subject (gvp:prefLabelGVP | xl:prefLabel | xl:altLabel)/xl:literalForm ?value .
      matches: |
        ?subject (skos:exactMatch | skos:closeMatch) ?value .
    wikidata_match_property: P245