# https://taskfile.dev

version: '3'

env:
  BLAZEGRAPH_ENDPOINT: http://blazegraph:8080/blazegraph/sparql
  BLAZEGRAPH_JOURNAL: /blazegraph-data/blazegraph.jnl
  BLAZEGRAPH_RUNNER: /utils/blazegraph-runner/bin/blazegraph-runner

tasks:

  update-data-aat:
    desc: Update data for Getty AAT
    vars:
      GRAPH: http://vocab.getty.edu/aat/graph
      DATA_DIRECTORY: /data/aat-data
      DATA_URL: http://aatdownloads.getty.edu/VocabData/explicit.zip
      GUNZIP: false
      FILE_FORMAT: nt
    cmds:
      - task: _downloadAndUnzip
        vars:
          URL: "{{.DATA_URL}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          GUNZIP: "{{.GUNZIP}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"
      - task: _removeGraphFromTripleStore
        vars:
          GRAPH: "{{.GRAPH}}"
      - task: _loadDataFromDirectory
        vars:
          GRAPH: "{{.GRAPH}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"

  update-data-geonames:
    desc: Update data for GeoNames
    vars:
      GRAPH: http://sws.geonames.org/graph
      DATA_DIRECTORY: /data/geonames-data
      DATA_URL: http://download.geonames.org/all-geonames-rdf.zip
      GUNZIP: false
      FILE_FORMAT: nt
    cmds:
      - task: _downloadAndUnzip
        vars:
          URL: "{{.DATA_URL}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          GUNZIP: "{{.GUNZIP}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"
      - echo "Preparing Geonames Data"
      - cp /pipeline/convert2ntriples.py {{.DATA_DIRECTORY}}/convert2ntriples.py; cd {{.DATA_DIRECTORY}}; python convert2ntriples.py; rm convert2ntriples.py; cd -
      - task: _removeGraphFromTripleStore
        vars:
          GRAPH: "{{.GRAPH}}"
      - task: _loadDataFromDirectory
        vars:
          GRAPH: "{{.GRAPH}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"
  
  update-data-gnd:
    desc: Update data for GND
    vars:
      GRAPH: https://d-nb.info/gnd/authorities/graph
      DATA_DIRECTORY: /data/gnd-authorities-data
      DATA_URL: https://data.dnb.de/opendata/authorities-gnd_lds.nt.gz
      GUNZIP: true
      FILE_FORMAT: ttl
    cmds:
      - task: _downloadAndUnzip
        vars:
          URL: "{{.DATA_URL}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          GUNZIP: "{{.GUNZIP}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"
      - task: _removeGraphFromTripleStore
        vars:
          GRAPH: "{{.GRAPH}}"
      - task: _loadDataFromDirectory
        vars:
          GRAPH: "{{.GRAPH}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"

  update-data-sikart:
    desc: TODO

  update-data-thesarchesp:
    desc: Update data for Thesaurus Architecture/Espace 
    vars:
      GRAPH: http://data.culture.fr/thesaurus/resource/ark:/67717/T96/graph
      DATA_DIRECTORY: /data/thes-arch-esp-data
      DATA_URL: http://data.culture.fr/thesaurus/data/ark:/67717/T96?includeSchemes=true&format=TURTLE
      GUNZIP: false
      FILE_FORMAT: ttl
    cmds:
      - task: _downloadAndUnzip
        vars:
          URL: "{{.DATA_URL}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          GUNZIP: "{{.GUNZIP}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"
      - task: _removeGraphFromTripleStore
        vars:
          GRAPH: "{{.GRAPH}}"
      - task: _loadDataFromDirectory
        vars:
          GRAPH: "{{.GRAPH}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"

  update-data-thesobjmob:
    desc: Update data for Thesaurus Object/Mobiliers
    vars:
      GRAPH: http://Fdata.culture.fr/thesaurus/resource/ark:/67717/T69/graph
      DATA_DIRECTORY: /data/thes-obj-mob-data
      DATA_URL: http://data.culture.fr/thesaurus/data/ark:/67717/T69?includeSchemes=true&format=TURTLE
      GUNZIP: false
      FILE_FORMAT: ttl
    cmds:
      - task: _downloadAndUnzip
        vars:
          URL: "{{.DATA_URL}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          GUNZIP: "{{.GUNZIP}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"
      - task: _removeGraphFromTripleStore
        vars:
          GRAPH: "{{.GRAPH}}"
      - task: _loadDataFromDirectory
        vars:
          GRAPH: "{{.GRAPH}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"

  update-data-ulan:
    desc: Update data for Getty ULAN
    vars:
      GRAPH: http://vocab.getty.edu/ulan/graph
      DATA_DIRECTORY: /data/ulan-data
      DATA_URL: http://ulandownloads.getty.edu/VocabData/full.zip
      GUNZIP: false
      FILE_FORMAT: nt
    cmds:
      - task: _downloadAndUnzip
        vars:
          URL: "{{.DATA_URL}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          GUNZIP: "{{.GUNZIP}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"
      - task: _removeGraphFromTripleStore
        vars:
          GRAPH: "{{.GRAPH}}"
      - task: _loadDataFromDirectory
        vars:
          GRAPH: "{{.GRAPH}}"
          DIRECTORY: "{{.DATA_DIRECTORY}}"
          FILE_FORMAT: "{{.FILE_FORMAT}}"

    
  _downloadAndUnzip:
    internal: True
    interactive: True
    desc: Download and unzip data
    requires:
      vars: [URL, DIRECTORY, GUNZIP, FILE_FORMAT]
    cmds:
      - # If the directory already exists, ask the user if they want to delete it
      - |
        if [ -d "{{.DIRECTORY }}" ]; then
          read -p "Do you want to remove previous data from the directory and download new ones? (y/n) " REPLY
          echo
          if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -r -d "{{.DIRECTORY}}"
          fi
        fi
      - # If the directory does not exist, download the data
      - |
        if [ ! -d "{{.DIRECTORY }}" ]; then
          mkdir -p "{{.DIRECTORY}}"
          cd "{{.DIRECTORY}}"
          echo "Fetching datasources..."
          if [ "{{.GUNZIP}}" == true ]; then
            curl -k {{.URL}} -o data.{{.FILE_FORMAT}}.gz
          else
            curl -k {{.URL}} -o data.zip
          fi
          echo "Fetching completed."
        fi

  _loadDataFromDirectory:
    desc: Load data from directory
    internal: True
    requires:
      vars: [GRAPH, DIRECTORY, FILE_FORMAT]
    cmds:
      - $BLAZEGRAPH_RUNNER load --journal=$BLAZEGRAPH_JOURNAL --graph={{.GRAPH}} {{.DIRECTORY}}/*.{{.FILE_FORMAT}}

  _removeGraphFromTripleStore:
    desc: Remove graph from triple store
    internal: True
    requires:
      vars: [GRAPH]
    cmds:
      - echo "DROP GRAPH <{{.GRAPH}}>" > tmp.rq
      - echo $BLAZEGRAPH_JOURNAL
      - $BLAZEGRAPH_RUNNER update --journal=$BLAZEGRAPH_JOURNAL tmp.rq
      - rm tmp.rq